.\" %Z%%M% %I% %E% SMI; from UCB 6.1 85/04/29
.TH XHTMLNEXT 1  "19 March 1995"
.SH NAME
xhtml \- a hypertext markup language editor program 
.SH SYNOPSIS
.B xhtml filename
.SH DESCRIPTION
.LP
.B xhtml
is a splitscreen HTML editor allowing amendments of
the source document and showing the HTML display of 
that source. The usual file editing facilities (open,
amend, save etc.) are present by either using meta key 
combinations or by mouse selection via pulldown menus. 
Also most of the HTML functions such as heading,
paragraphs, lists etc are available.
  

.LP
.SH FILES
.PD 0
.TP 20
The xhtml wiget lib files are found in the directory:
.B /usr/lib/X11/libhtmlw
.LP
.SH SEE ALSO
.BR xhtml
.\" SCO

