#!/bin/sh
#
# configure-sco - a front-end to configure for use on SCO OpenServer 5
#
# To build with gcc, invoke as configure-gcc
#

RANLIB=/bin/true
M4=/usr/local/bin/m4
LD="ld -belf"
INSTALL="/usr/bin/X11/scoinst  -c"
TCL_PREFIX=/usr/local
TK_PREFIX=/usr/local

MYNAME=`basename $0`

if [ "$MYNAME" = "configure-gcc" ]
then
	echo "Configuring with gcc"
	CC="gcc -melf"
else
	CC="cc -belf"
fi

export CC LD INSTALL RANLIB M4 TCL_PREFIX TK_PREFIX

./configure $*
