#!/bin/sh

cd /u/Forum/2005
rm -rf html
mkdir html
rm -f /tmp/owc15 /tmp/ols15
./setup
#mgp -Q 100 -g 1024x768 -D html opensource.mgp
mgp -U -Q 100 -D html opensource.mgp
rm -f core
rm -f /tmp/owc15 /tmp/ols15
chmod 755 html
chmod a+r html/*
