<table border="0" cellspacing="0" cellpadding="0" align="left" width="150">
<tr>
    <td valign="top" width="140" align="left">
    <a href="/skunkware/whatsnew.html">
    <IMG SRC="/skunkware/graphics/whatsnew.gif" WIDTH=140 HEIGHT=29 BORDER=0 
     ALT= "What's New!"></a>
    <a href="/skunkware/98/">
    <IMG SRC="/skunkware/graphics/sk98.gif" WIDTH=140 
     HEIGHT=42 BORDER=0 ALT="Skunkware 98 for OpenServer"></a>
    <a href="/skunkware/uw7/">
    <IMG SRC="/skunkware/graphics/skunk7.gif" 
    WIDTH=140 HEIGHT=42 BORDER=0 ALT="Skunkware 7 for UnixWare"></a>
    <a href="/skunkware/relnotes.html">
    <IMG SRC="/skunkware/graphics/release.gif" WIDTH=140 HEIGHT=29 BORDER=0 
     ALT="Release Notes"></a>
    <a href="/skunkware/faq.html">
    <IMG SRC="/skunkware/graphics/qanda.gif" WIDTH=140 HEIGHT=29 BORDER=0 
     ALT="Questions and Answers"></a>
    <a href="http://www.sco.com/developer/">
    <IMG SRC="/skunkware/graphics/devplce.gif" WIDTH=140 HEIGHT=29 BORDER=0 
     ALT="Visit Developer's Place"></a>
    <a href="/skunkware/credits.html">
    <IMG SRC="/skunkware/graphics/acknow.gif" WIDTH=140 HEIGHT=29 BORDER=0 
     ALT="Acknowledgements"></a>
    <a href="/skunkware/">
    <IMG SRC="/skunkware/graphics/skunkforweb.gif" 
     WIDTH="100" HEIGHT="93" BORDER="0" ALIGN="right" ALT="Skunkware Home"></a>
    </td>
    <td></td>
</tr>

<tr>
    <td width="140"><p align="right"><font face="arial, helvetica" size="-2"><b>
    <a href="http://www.sco.com/copyright/">
    Copyright</a> &copy; 1996-1999 The Santa Cruz Operation, Inc.
    <br>All Rights Reserved.</b></font></td><td>&nbsp;</td>
</tr>
</table>
