<!--Begin navigation panel-->

<table class="nav" width="150" align="left" cellpadding="0" cellspacing="0" bgcolor="#ffcc33" border="0">
<tr>
<td valign="top" width="150" bgcolor="#ffCC33" colspan="2">
<img src="/ssi/toolbar/invis.gif" width="150" height="10" border="0">
</td>
</tr>
<tr>
<td valign="top" width="18" bgcolor="#ffCC33">
<img src="/ssi/toolbar/invis.gif" width="18" height="10" border="0">
</td>
<td valign="top" width="132" bgcolor="#ffCC33">

<!--Begin adding link and navigation items - see http://spin.sco.com/box/-->
<!--Begin adding link and navigation item-->

<p class="navarea"><a href="/skunkware/whatsnew.html">What's New</a></p>
<p class="navarea"><a href="/skunkware/98/">Skunkware 98<br> for OpenServer</a></p>
<p class="navarea"><a href="/skunkware/uw7/">Skunware 7 <br> for UnixWare</a></p>
<p class="navarea"><a href="/skunkware/relnotes.html">Release Notes</a></p>
<p class="navarea"><a href="/skunkware/faq.html">Q & A</a></p>
<p class="navarea"><a href="/developer/">Developers</a></p>
<p class="navarea"><a href="/skunkware/credits.html">Acknowledgements</a></p>


<!--End adding link and navigation item-->
<!--For more items, copy and paste the above-->
<!--End link and navigation items-->


<img src="/ssi/toolbar/invis.gif" width="132" height="10" border="0"></td></tr></table>

<!--End navigation panel-->