<br clear="all">

<table border="0" cellpadding="0" cellspacing="0" width="100%"  bgcolor="#ffffff">
<tr><td valign="top" height="15">

<p><img src="/ssi/copyright/invis.gif" width="1" height="15" BORDER="0"></p></td></tr></table>


<table border="0" cellpadding="0" cellspacing="0" width="100%"  bgcolor="#003399">
<tr><td valign="top" height="6">

<p><img src="/ssi/copyright/invis.gif" width="1" height="6" BORDER="0"></p></td></tr></table>

<p class="copyright"><a href="/fr/copyright">Copyright</a> &copy; 1995-2000 The 
  Santa Cruz Operation, Inc. Tous droits réservés. <a href="/fr/copyright/privacy.html">Confidentialité</a>. 
  <a href="http://www.sco.com/"><img src="/ssi/copyright/sco_copyright.gif" width="30" height="20" border="0" alt="Page d´accueil SCO" hspace="10"></a></p>
