<br clear="all">
<TABLE CELLPADDING="0" CELLSPACING="0" BORDER="0" width="100%"  bgcolor="#003399">

<tr><td valign="top" height="6">

<p><img src="/ssi/copyright/yellow.gif" width="340" height="3" BORDER=0 align="bottom"></p></td></tr></table>

<p class="copyright"><a href="http://www.sco.com/copyright">Copyright</a> &copy; 1996-1999 The Santa Cruz Operation, Inc. All Rights Reserved. <a href="http://www.sco.com/"><img src="/ssi/copyright/sco_copyright.gif" width="30" height="20" border="0" alt="SCO Home Page"></a></p>
