#!/bin/sh

P=`pwd`
N=`basename $P`
PKGTAR=$N-VOLS.tar
PKGDIST=$N-dist.cpio.gz

DIRS=usr
[ -d etc ] && DIRS="etc usr"
cd archives/FLOPPY
tar cf ../../$PKGTAR VOL*
cd ../..
#tar cf - $DIRS | /usr/local/bin/gzip -9 > $PKGDIST
find $DIRS -depth -print | cpio -oc -O${N}-dist.cpio
gzip -9 ${N}-dist.cpio
[ -f $PKGTAR ] && rm -rf archives
[ -f $PKGDIST ] && rm -rf $DIRS
rm -rf sso
