#!/bin/sh

#
# Edit the following setting of MOUNTPT to be wherever you have
# mounted the SCO Skunkware 96 CD-ROM. By default, i have set it
# to /mnt. If you mounted the SCO Skunkware 96 CD-ROM on /usr/skunk96,
# then you would set MOUNTPT=/usr/skunk96
#

MOUNTPT=/mnt

#
# ------------------------------------------------------------------
#
# In order to easily access many of the installed SCO Skunkware 96
# components, you may wish to add /usr/local/bin to your PATH and
# /usr/local/man to your MANPATH. For instance, a Bourne shell user
# could add the following to their $HOME/.profile :
# 
# 	PATH=$PATH:/usr/local/bin
# 	MANPATH=$MANPATH:/usr/local/man
# 	export PATH MANPATH
# 
# The system administrator can set these on a system-wide basis by
# modifying the files /etc/default/login and /etc/default/man.
#
# ------------------------------------------------------------------

getyn() {
	ans=
	while [ "$ans" = "" ]
	do
		read ans
		[ "$ans" = "Y" ] || [ "$ans" = "y" ] && {
			ans=Y
			break
		}
		[ "$ans" = "n" ] || [ "$ans" = "N" ] && {
			ans=N
			break
		}
		ans=
		echo "\nPlease answer with a Y or N \c"
	done
}

echo "\nWould you like to install all of the SCO Skunkware 96 custom"
echo "installable software to your hard disk at this time ? <Y/N> \c"

getyn

if [ "$ans" = "Y" ] 
then
	custom -p SKUNK96:default -i -z $MOUNTPT/inst/All
else
	echo "\nYou can install one or more of the SCO Skunkware 96"
	echo "custom installable components at a later time by copying"
	echo "this file (<mount-point>/INSTALL) to your hard disk,"
	echo "and uncommenting the line or lines for the component(s)"
	echo "you wish to install. You may also need to modify the"
	echo "MOUNTPT variable (set by default to /mnt)."
	echo "After doing this, simply execute the INSTALL program (as root)."
fi
# ------------------------------------------------------------------
#
# Uncomment the lines below which contain the packages you'd like installed
# and then run this file as root as a shell script (# sh INSTALL) or, as root,
# issue any of the following at a shell prompt :
#
# To install all of the SCO Skunkware 96 custom installable components,
# uncomment the following two lines.
#
#custom -p SKUNK96:default -i -z $MOUNTPT/inst/All
#custom -p SCO:gds -i -z $MOUNTPT/inst/gds
#
# To install individual components, uncomment those desired
#
#custom -p SKUNK96:default:Tcl -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:TclX -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:TK -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Zircon -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:freeWAIS -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Ghostscript -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Ghostview -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:GZIP -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Lynx -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Mpeg_bits -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Mpeg_blocks -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Mpeg_encode -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Mpeg_stat -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Netpbm -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Perl5 -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Vat -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:XHTML -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Fvwm -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Mpeg_play -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Xanim -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Xarchie -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Xdaliclock -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:XDir -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Xfig -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:XFtp -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Xmcd -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Xmorph -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Xpdf -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:Xpm -i -z $MOUNTPT/inst/All
#custom -p SKUNK96:default:XV -i -z $MOUNTPT/inst/All
