
The latest Skunkware handoff of Obtuse Smtpd from Ed Hew 
is release 1.0.3a for SCO OpenServer. To install this release,
extract the gzip'd tar archive in /usr/local/src :

    # [ -d /usr/local/src ] || mkdir -p /usr/local/src
    # cd /usr/local/src
    # gzcat /path/to/obtuse-smtpd-1.0.3a-osr5.tar.gz | tar xf -
    # cd obtuse-smtpd
    # sh INSTALL.SCO-MMDF

To install for use in conjunction with Sendmail, see the instructions
in the file INSTALL.sendmail.
