#!/bin/sh

echo "
NOTE: To use smake-1.2a02 on SCO OpenServer 5 to compile cdrtools-1.8a??
      you need to increase the \"maxexecargs\" kernel parameter in
      /etc/conf/pack.d/kernel/space.c to at least 200*1024 !!!!
      
      If you need further information on maxexecargs please see
      
      http://www.sco.com/cgi-bin/ssl_reference?105076
"
