#!/bin/sh

cd /u/Forum/Forum2002
mgp2ps -p letter -f skunkware.ps skunkware-print.mgp

#     Alternately
#
# rm -rf ps
# mkdir ps
#
# cd html
# for i in mgp000??.gif
# do
#     p=`echo $i | sed -e "s/.gif/.ps/"`
#     gif2ps -i $i > ../ps/$p
# done
