<form action="/cgi-bin/gosite" name="siteNav" method="GET">
<table border="0" cellpadding="0" cellspacing="0" width="100%"  bgcolor="#FFCC00">
<tr><td valign="top" height="6"><img src="/ssi/toolbar/invis.gif" width="1" height="6" border="0"></td></tr></table>

<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="150" valign="top" rowspan="2" height="61">
<a href="http://www.sco.com/"><img src="/ssi/toolbar/toollogo.gif" width="70" height="51" border="0" alt="SCO"></a></td>
<td bgcolor="#003399" align="middle" width="390" height="51" valign="bottom">


<img src="/ssi/toolbar/invis.gif" width="20" height="1" border="0">
<INPUT TYPE="HIDDEN" Name="DB" Value="test"><INPUT name="P" SIZE="10"><img src="/ssi/toolbar/invis.gif" width="5" height="1" border="0"><INPUT type="image" border="0" value="Find" src="/ssi/toolbar/toolsea.gif" width="45" height="44" alt="Search SCO"><img src="/ssi/toolbar/invis.gif" width="20" height="1" border="0"><a href="http://www.sco.com/feedback/"><img src="/ssi/toolbar/toolcon.gif" width="76" height="44" border="0" alt="Contact SCO"></a><img src="/ssi/toolbar/invis.gif" width="20" height="1" border="0"><a href="http://www.sco.com/"><img src="/ssi/toolbar/toolhom.gif" width="33" height="44" border="0" alt="SCO Home Page"></a><img src="/ssi/toolbar/invis.gif" width="20" height="1" border="0"></td></tr>

<tr><td height="10"><img src="/ssi/toolbar/invis.gif" width="15" height="10" border="0"></td></tr></table>