#!/bin/sh

TOPD=/v/sco_ftp
IDIR=skunkware/incoming

cd $TOPD

echo "#!/bin/sh

cd $TOPD

tar cf $IDIR/new.tar
" > $IDIR/new

find skunkware -newer $IDIR/last -print >> $IDIR/new
rm -f $IDIR/last
mv $IDIR/new $IDIR/last
vi $IDIR/last
sh $IDIR/last
