#!/bin/sh

H=`pwd`
PKG=`basename $H`
VDIR=archives/FLOPPY
DDIR=

[ -d $VDIR ] && {
   cd $VDIR
   tar cf $H/$PKG-VOLS.tar V*
   cd $H
}

for i in usr bin lib etc
do
   [ -d $i ] && DDIR="$DDIR $i"
done

[ "$DDIR" ] && tar cf - $DDIR | gzip -9 > $PKG-dist.tar.gz

rm -rf archives sso usr bin lib etc
