#!/bin/sh

cd /u/Forum/2006
rm -f /tmp/owc15 /tmp/ols15
./setup
if [ "$1" = "-g" ]
then
    mgp -U -Q 100 -g 1024x768 opensource.mgp &
else
    if [ "$1" = "-d" ]
    then
        mgp -V -U -Q 100 opensource.mgp &
    else
        mgp -U -Q 100 opensource.mgp &
    fi
fi
#rm -f /tmp/owc15 /tmp/ols15
