.\" @(#) $Header: arpwatch.8,v 1.4 94/09/19 12:54:37 leres Exp $ (LBL)
.\"
.\" Copyright (c) 1992, 1994
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that: (1) source code distributions
.\" retain the above copyright notice and this paragraph in its entirety, (2)
.\" distributions including binary code include the above copyright notice and
.\" this paragraph in its entirety in the documentation or other materials
.\" provided with the distribution, and (3) all advertising materials mentioning
.\" features or use of this software display the following acknowledgement:
.\" ``This product includes software developed by the University of California,
.\" Lawrence Berkeley Laboratory and its contributors.'' Neither the name of
.\" the University nor the names of its contributors may be used to endorse
.\" or promote products derived from this software without specific prior
.\" written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
.\"
.TH ARPWATCH 8 "19 Sep 1994"
.UC 4
.SH NAME
arpwatch - keep track of ethernet/ip address pairings
.SH SYNOPSIS
.B arpwatch
[
.B -d
] [
.B -i
.I interface
]
.SH DESCRIPTION
.B Arpwatch
keeps track for ethernet/ip address pairings. It reports certain
changes via email.
.LP
The
.B -i
flag is used to override the default interface.
.LP
The
.B -d
flag is used enable debugging. This also inhibits mailing the reports.
Instead, they are sent to
.IR stderr .
.LP
Note that an empty
.I arp.dat
file must be created before the first time you run
.BR arpwatch .
.LP
.SH FILES
.na
.nh
.nf
/usr/operator/arpwatch - default directory
arp.dat - ethernet/ip address database
ethercodes.dat - vendor ethernet block list
.ad
.hy
.fi
.SH "SEE ALSO"
.na
.nh
.BR arp (8),
.BR bpf (4),
.BR pcap (3)
.ad
.hy
.SH BUGS
Attempts are made to suppress DECnet flip flops but they
aren't always successful.
