#!/bin/sh
#
# Generic command-line Software Manger (custom) removal from
# media images. Based on the installation script by Phil Hollenback 
# (philiph@sco.com) and Ron Record (rr@sco.com)
#

# Set this to be the full pathname to the directory 
# where your media images are:
VDIR=`pwd`/archives/TAPE
VOLS=$VDIR/VOL.000.000

component=`/bin/grep "component" < $VOLS | /bin/head -1 | \
           /usr/bin/cut -d= -f2 | /usr/bin/cut -d: -f1`
package=`/bin/grep "component" < $VOLS | /bin/head -1 | \
         /usr/bin/cut -d= -f2 | /usr/bin/cut -d: -f2`

custom -p $component:$package -r
