#!/bin/ksh
# @(#) u.ksh 1.0 95/10/24
# 95/10/24 john h. dubois iii
set -A u $(who -q)
# get rid of '# users=n'
unset u[${#u[*]}-1] u[${#u[*]}-2]
# sort userlist
set -s -A u -- "${u[@]}"
# print usernames with fixed field with; this will also end up column-aligned
# on an 80 column display with linewrap on, while still having the single-line
# output format for the sake of things that read 1 line from u
typeset -L9 u
print -r -- "${u[*]}"
