
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr> 
    <td valign="middle" height="10" bgcolor="#FFCC00" colspan="2"> 
      <div align="right"><img src="ssi/toolbar/invis.gif" width="1"
height="1" hspace="10" border="0" alt=""></div>
    </td>
  </tr>
  <tr>
    <form method="GET" action="http://search.sco.com/cgi-bin/empower"
name="siteNav">
      <td valign="top" height="43" bgcolor="#003399"><a
href="http://www.sco.com/" onMouseOver="window.status='SCO'; return true" onMouseOut="window.status='SCO & UNIX
UNIX'; return true"><img src="ssi/toolbar/toollogosm.gif" width="75"
border="0" height="43" alt="SCO"></a><a href="/taiwan/"
onMouseOver="window.status='SCO'; return true"
onMouseOut="window.status='SCO& UNIX'; return
true"><img src="/ssi/toolbar/taiwan/tool_taiw.gif" width="95" border="0"
height="43" alt="SCO Taiwan"></a><a href="/profservices/linux/"
onMouseOver="window.status='New Linux Services'; return true"
onMouseOut="window.status='SCO & UNIX'; return
true"><img src="/ssi/toolbar/hot_linux.gif" width="70" height="43"
border="0" alt="New Services Linux"></a><img src="/ssi/toolbar/invis.gif" width="17" height="1"
border="0"><a href="http://www.sco.com/year2000/"
onMouseOver="window.status='SCO & Year 2000'; return true"
onMouseOut="window.status='SCO & UNIX'; return
true"><img src="/ssi/toolbar/hoty2k.gif" width="49" height="43" border="0"
alt="Year 2000"></a><img
src="/ssi/toolbar/invis.gif" width="17" height="1" border="0"><a
href="http://www.sco.com/forum1999/" onMouseOver="window.status='SCO Forum
1999'; return true" onMouseOut="window.status='SCO :
& UNIX'; return true"><img
src="/ssi/toolbar/hotforum.gif" width="59" height="43" border="0" alt="SCO
Forum 1999"></a></td>
      <td valign="MIDDLE" height="20" bgcolor="#003399">
        <div align="right">
          <input
type="HIDDEN" name="DB" value="rest">
          <input name="QUERY00" size="8">
          <img
src="/ssi/toolbar/invis.gif" width="1" height="1" border="0"> 
          <input
type="image" border="0" value="Find" src="/ssi/toolbar/taiwan/toolsea.gif"
width="40" height="15" alt="Search SCO" name="image">
          <img src="/ssi/toolbar/invis.gif"
width="1" height="1" border="0"><a href="http://www.sco.com/feedback/"
onMouseOver="window.status='Contact'; return true"
onMouseOut="window.status='SCO : l&rsquo;avenir d&rsquo;UNIX'; return
true"><img src="/ssi/toolbar/taiwan/toolcon.gif" width="49" height="15" border="0"
alt="Contact, feedback and questions"></a><img src="/ssi/toolbar/invis.gif"
width="1" height="1" border="0"></div>
      </td>
    </form>
  </tr>
  <tr> 
    <td valign="top" colspan="2" height="11"><img src="ssi/toolbar/invis.gif"
width="1" height="1" border="0"></td>
  </tr>
</table>
