.TH FMT 1
.SH NAME
fmt - adjust line-length for paragraphs of text
.SH SYNOPSIS
\fBfmt\fP [\fB\-\fIwidth\fR] [\fIfiles\fP]...
.SH DESCRIPTION
This page describes the \fIelvis\fR version of
.IR fmt .
.PP
.I fmt
is a simple text formatter.
It inserts or deletes newlines, as necessary, to make all lines in a
paragraph be approximately the same width.
It preserves indentation and word spacing.
.PP
The default line width is 72 characters.
You can override this with the
.BI - width
flag.
If you don't name any files on the command line, then
.I fmt
will read from stdin.
.PP
It is typically used from within
.BR elvis (1)
to adjust the line breaks in a single paragraph.
To do this, move the cursor to the top of the paragraph,
type "!}fmt", and hit <Enter>.
.SH AUTHOR
.nf
Steve Kirkendall
kirkenda@cs.pdx.edu
.fi
