
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr> 
    <td valign="middle" height="10" bgcolor="#FFCC00" colspan="2"> 
      <div align="right"><img src="/ssi/toolbar/france/invis.gif" width="1"
height="1" hspace="10" border="0" alt=""></div>
    </td>
  </tr>
  <tr>
    <form method="GET" action="http://search.sco.com/cgi-bin/empower"
name="siteNav">
      <td valign="top" height="43" bgcolor="#003399"><a
href="http://www.sco.com/" onMouseOver="window.status='Page d\'accueil de SCO'; return true" onMouseOut="window.status='SCO : l\'avenir d\'UNIX '; return true"><img src="/ssi/toolbar/france/toollogosm.gif" width="75"
border="0" height="43" alt="SCO"></a><a href="/france/"
onMouseOver="window.status='Page d\'accueil de SCO France'; return true"
onMouseOut="window.status='SCO : l\'avenir d\'UNIX'; return
true"><img src="/ssi/toolbar/france/tool_france.gif" width="95" border="0"
height="43" alt="SCO France"></a><a href="/linux/"
onMouseOver="window.status='Linux \& Open Source'; return true"
onMouseOut="window.status='SCO : l\'avenir d\'UNIX'; return
true"><img src="/ssi/toolbar/france/hot_linux.gif" width="66" height="43"
border="0" alt="Linux et Open Source"></a><img src="/ssi/toolbar/invis.gif" width="17" height="1"
border="0"><a href="http://www.sco.com/year2000/"
onMouseOver="window.status='SCO et l\'an 2000'; return true"
onMouseOut="window.status='SCO : l\'avenir d\'UNIX'; return
true"><img src="/ssi/toolbar/france/hoty2k_fr.gif" width="53" height="43" border="0"
alt="L'an 2000"></a><img
src="/ssi/toolbar/france/invis.gif" width="17" height="1" border="0"><a href="/forum2000/"
onMouseOver="window.status='Forum SCO 2000'; return true"
onMouseOut="window.status='SCO : l\'avenir d\'UNIX'; return
true"><img src="/ssi/toolbar/france/hotforum_fr.gif" width="60" height="43"
border="0" alt="Forum SCO 2000"></a></td>
      <td valign="MIDDLE" height="20" bgcolor="#003399">
        <div align="right">
          <input
type="HIDDEN" name="DB" value="rest">
          <input name="QUERY00" size="8">
          <img
src="/ssi/toolbar/france/invis.gif" width="1" height="1" border="0"> 
          <input
type="image" border="0" value="Find" src="/ssi/toolbar/france/toolsea.gif"
width="66" height="15" alt="Search SCO" name="Recherche">
          <img src="/ssi/toolbar/france/invis.gif"
width="1" height="1" border="0"><a href="http://www.sco.com/feedback/"
onMouseOver="window.status='Des questions ou suggestions : contactez-nous'; return true"
onMouseOut="window.status='SCO : l\'avenir d\'UNIX '; return
true"><img src="/ssi/toolbar/france/toolcon.gif" width="98" height="15" border="0"
alt="Des questions ou suggestions : contactez-nous"></a><img src="/ssi/toolbar/france/invis.gif"
width="6" height="1" border="0"></div>
      </td>
    </form>
  </tr>
  <tr> 
    <td valign="top" colspan="2" height="11"><img src="/ssi/toolbar/france/invis.gif"
width="1" height="1" border="0"></td>
  </tr>
</table>
