#!/bin/sh

[ -f mout-config ] && mv mout-config mout-config$$

if [ "`basename $0`" = "configure-svr5-binutils" ]
then
    echo "./configure --gas --with-gnu-binutils $* --host=i386-sco-sysv4 --target=i386-sco-sysv4 2>&1 | tee mout-config"
    ./configure --gas --with-gnu-binutils $* --host=i386-sco-sysv4 --target=i386-sco-sysv4 2>&1 | tee mout-config
else
    if [ "`basename $0`" = "configure-svr5-cc" ]
    then
        CC=cc
        CXX=CC
        RANLIB=true
        MAKE=/usr/local/bin/make
        export CC CXX RANLIB MAKE
	fi
    echo "./configure $* --host=i386-sco-sysv4 --target=i386-sco-sysv4 2>&1 | tee mout-config"
    ./configure $* --host=i386-sco-sysv4 --target=i386-sco-sysv4 2>&1 | tee mout-config
fi
