#!/bin/sh
#
# Configure - useful front-end to configure. To use, create a subdirectory
#             in the top-level source hierarchy you wish to build. Change
#             directory into that subdirectory and run this script.
#             This allows you to do multiple builds of the same source tree
#             by running "configure" from different subdirectories.
#
# Written 10-Oct-97 by Ron Record (rr@sco.com)
#

[ -f mout-config ] && mv mout-config mout-config$$

RANLIB=true
MAKE=/usr/local/bin/make
CFLAGS=-O2
CXXFLAGS=-O2
SHFLAGS="-h /usr/local/lib/\$(SHLIB)"
export RANLIB MAKE CFLAGS CXXFLAGS SHFLAGS

if [ "`basename $0`" = "Configure-cc" ]
then
    CC=cc
    CXX=CC
    export CC CXX
fi
H=`pwd`
echo "$H/../configure --host=i386-sco-sysv4 --target=i386-sco-sysv4 2>&1 | tee mout-config"
$H/../configure --host=i386-sco-sysv4 --target=i386-sco-sysv4 2>&1 | tee mout-config
